### ISSUE TITLE
Implement rate limiting filter

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#138]
Please implement a rate limiting filter.

Initial set of functions:

* You configure a timespan in seconds and the amount of requests allowed in this time span
* The filter counts the amount of requests for each user. If the requests exceed the allowed number then it throws an appropriate exception
* The request counter is an in-memory data structure. Please create an interface so it can be easily exchanged.
* Please take care for concurrent access.

Future set of functions (in this order)

* Track and rate-limit anonymous users.
* Configure rate-limiting per endpoint.
* Externalize configuration.
* Configure higher rate limits for individual users.

**Comment by m1ci** [comment]
what about limiting the size of the content we process? This will help us avoid processing very long documents.
We need to agree on what the maximum length of documents we accept.

**Comment by josauder** [comment]
A prototype is up and running in the `broker:rate-limiter` branch.

You can try it out by starting the Broker and spamming any kind of calls to the API
Users are mapped by their username - anonymous/unauthenticated users are mapped by their IP - this is not final and should be reconsidered.
External Configuration moved do `application.properties` file.

### Todos in descending order of importance:
* fix rateLimiterInMemory.setup() because the `@Value` Annotation seems to only work for strings not numbers
* Enable Scheduling and Schedule the rateLimiters so that all stored Timestamps are deleted after a configurable time frame, see [here](https://spring.io/guides/gs/scheduling-tasks/)

> Configure rate-limiting per endpoint.
Externalize configuration.
Configure higher rate limits for individual users.

* Possibly optimize, makes sense only when all features are built in

**Comment by josauder** [comment]
This is fully implemented in `rate-limiter` branch. It can be merged into master. 

## Configuration of RateLimitingFilter
### application.properties ###

* `ratelimiter.enabled` - decides if this filter should be used at all. If `false` all other parameters will be irrelevant
* `ratelimiter.clear.timer` - specifies time in miliseconds until all stored timestamps/sizes of previous requests will be deleted. Defaults to `Integer.MAX_VALUE` which clears the filter approximately every 24 days.
* `ratelimiter.yaml` - specifies path to ratelimiter.yaml configuration file used. Defaults to `src/main/resources/ratelimiter.yaml`

### ratelimiter.yaml 

```
time-frame: 600   # time period in seconds
rate-limits:
  ROLE_ANONYMOUS:
    default:
      - 50
      - 1000 # anomyous user has 50 requests or 1000 kb in the time period
    /e-entity/freme-ner/documents:
      - 10
      - 1000000 # override for anonymous user to allow 50 requests or 1000 mb in the time period
  ROLE_USER:
    default:
      - 30
      - 1000 # anomyous user has 50 requests or 1000 kb in the time period
    /freme-ner/datasets:
      - 50
      - 2000000 # override for authenticated users to allow 50 requests or 2000 mb in the time period
  ROLE_ADMIN:
    default:
      - 0
      - 0 # admin user has no rate limits configured
  henry:
    /e-translation/tilde:
      - 50
      - 10000 # user henry has a special override on tilde
```
Every request will search these properties in the following order:

1. - `ratelimits.<username-or-ip>.<requested-endpoint>`
2. - `ratelimits.<username-or-ip>.default`
3. - `ratelimits.<role-of-caller>.<requested-endpoint>`
4. - `ratelimits.<role-of-caller>.default`
5. - Throw internal server error `"No identifier found for "+<username-or-ip>+"with role"+ <role-of-caller> + "for resource" + <requested-endpoint>`

To do this, the usernames `ROLE_ANONYMOUS`, `ROLE_USER`, and `ROLE_ADMIN` are not permitted anymore in the UserController

Sizes of requests made are determined the request-body size. If this is 0 and the input query field is not empty, will take length of the input instead.
